name: Main

on:
  push:
    branches:
      - main
    tags:
      - "v**"
  pull_request:
    branches:
      - main
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
  integration-test:
    strategy:
      matrix:
        # docker isn't available on macox-latest or windows-latest
        os: [ubuntu-latest]
        rust: [stable]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
          targets: x86_64-unknown-linux-musl
      - name: Install MUSL tools
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y musl-tools
      - name: Test
        shell: bash
        run: npm run test:integration
  # publish:
  #   needs: [unit-test, integration-test]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Publish
  #       if: startsWith(github.ref, 'refs/tags/')
  #       run: |
  #         npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
  #         npm publish
  #       env:
  #         CI: true
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
